# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven


on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-24.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run unit and integration tests
        env:
          JAVA_TOOL_OPTIONS: -Djava.awt.headless=true
        run: mvn -X test
      - name: Generate JaCoCo coverage report
        run: mvn jacoco:report

      - name: Upload JaCoCo coverage report to GitHub summary
        run: echo "JaCoCo Coverage Report:" >> $GITHUB_STEP_SUMMARY
             && cat target/site/jacoco/index.html >> $GITHUB_STEP_SUMMARY


  multi-os-testing:
    name: Multi-OS Testing
    needs: build-and-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-24.04]

    steps:
      - name: Parallel Tests
        run: echo "Tests executed on ${{ matrix.os }}"
