name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Déclenche le workflow sur des pushs vers la branche main
  pull_request:
    branches:
      - main  # Déclenche le workflow sur des pull requests vers la branche main
  workflow_dispatch:  # Permet un déclenchement manuel du workflow depuis GitHub

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest  # Utilisation d'un runner Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Action pour récupérer le code source du dépôt

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin  # Utilisation d'OpenJDK 17

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests  # Installe les dépendances sans exécuter les tests

      - name: Run unit and integration tests
        run: mvn test  # Exécute les tests unitaires
