name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest  # Utilisation d'un runner Ubuntu

    services:
      postgres:
        image: postgres:13  # Version de PostgreSQL que vous souhaitez utiliser
        env:
          POSTGRES_DB: postgres  # Nom de la base de données à créer
          POSTGRES_USER: postgres  # Utilisateur de la base de données
          POSTGRES_PASSWORD: task_manager  # Mot de passe pour l'utilisateur
        ports:
          - 5432:5432  # Expose le port PostgreSQL (5432 par défaut)
        options: >-
          --health-cmd="pg_isready -U user -d testdb"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Maven
        uses: actions/setup-maven@v3
        with:
          maven-version: '3.8.4'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run unit and integration tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: "postgres"
          SPRING_DATASOURCE_PASSWORD: "postgres"
        run: mvn test
